package com.shopped.api.model;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Cart
 */
@DynamoDBTable(tableName = "CART_TABLE")
public class Cart {
    private String id;
    private Map<String, String> items;
    private String author;
    private String status;

    public Cart(@JsonProperty("items") Map<String, String> items, @JsonProperty("id") String id,
            @JsonProperty("author") String author, @JsonProperty("status") String status) {
        this.items = items;
        this.author = author;
        this.status = status;
        this.id = id;
    }

    public Cart(String id, String author) {
        this.id = id;
        this.author = author;
    }

    public Cart() {
    }

    public Cart(String author) {
        this.author = author;
    }

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "AUTHOR")
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @DynamoDBAttribute(attributeName = "STATUS")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "ITEMS")
    public Map<String, String> getItems() {
        return items;
    }

    public void setItems(Map<String, String> items) {
        this.items = items;
    }

    public void addItem(String name, String amount) {
        this.items.put(name, amount);
    }

}
